live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = false
opacity = 0.95

[window.padding]
x = 5
y = 5

[font]
size=14.0

[font.bold]
family = "FantasqueSansM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FantasqueSansM Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FantasqueSansM Nerd Font"
style = "Italic"

[font.normal]
family = "FantasqueSansM Nerd Font"
style = "Regular"

import = [
	"~/.config/alacritty/catppuccin/catppuccin-mocha.toml",
	]
