palette = "catppuccin_macchiato"

format = """
[](sky)\
$os\
$username\
[](bg:green fg:sky)\
$directory\
[](fg:green bg:pink)\
$git_branch\
$git_status\
[](fg:pink bg:sapphire)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$python\
[](fg:sapphire bg:blue)\
$docker_context\
[ ](fg:blue)\
"""

right_format = """
[](fg:sky)\
$localip
$time\
[](sky)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:sky fg:surface0"
style_root = "bg:sky fg:surface0"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:sky fg:surface0"
disabled = false # Disabled by default

[localip]
style = "bg:sky fg:surface0"
disabled = false # Disabled by default
ssh_only = false
format = '[ \($localipv4\)]($style)'


[directory]
style = "bg:green fg:surface0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by base replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:blue fg:surface0"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:pink fg:surface0"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:pink fg:surface0"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:sapphire fg:surface0"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:sky fg:surface0"
format = '[ 󰥔 $time ]($style)'

# ------------------- Catpuccin -------------------

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
